services:
  plex-server:
    container_name: plex-server
    image: plexinc/pms-docker:latest@sha256:83a425ae9e133b1cb2cc3b809556e01c61cd8ff65c582e41b4374bc2210bac9e
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Paris # timezone, defined in .env
      - HOSTNAME=plex@home
    volumes:
      - plex_config:/config # plex database
      - /mnt/media:/data:ro # media library

volumes:
  plex_config:
    name: plex_config
