services:
  plex-server:
    container_name: plex-server
    image: plexinc/pms-docker:latest@sha256:e0ab27395614a8e1a4fdf84c6bc60ac664915cfdde70c52d030c7728a1c48e14
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Paris # timezone, defined in .env
      - HOSTNAME=plex@home
    volumes:
      - plex_config:/config # plex database
      - /mnt/media:/data:ro # media library

volumes:
  plex_config:
    name: plex_config
